name: Docker

on:
  workflow_call:

jobs:
  docker:
    name:  Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: luancardosoti@gmail.com
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
   

  
